//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opozee.Models.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OpozeeDbEntities : DbContext
    {
        public OpozeeDbEntities()
            : base("name=OpozeeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookMark> BookMarks { get; set; }
        public virtual DbSet<Opinion> Opinions { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Bounty> Bounties { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Referral> Referrals { get; set; }
        public virtual DbSet<Follower> Followers { get; set; }
    
        public virtual ObjectResult<SP_GetTopLikes_Result> SP_GetTopLikes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTopLikes_Result>("SP_GetTopLikes");
        }
    
        public virtual ObjectResult<SP_GetBountyQuestions_Result> SP_GetBountyQuestions(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetBountyQuestions_Result>("SP_GetBountyQuestions", startDateParameter, endDateParameter);
        }
    
        public virtual int SP_SetBountyQuestions(Nullable<int> questionId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> isActive)
        {
            var questionIdParameter = questionId.HasValue ?
                new ObjectParameter("QuestionId", questionId) :
                new ObjectParameter("QuestionId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SetBountyQuestions", questionIdParameter, startDateParameter, endDateParameter, isActiveParameter);
        }
    }
}
