//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opozee.Models.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public partial class Token
    {
        public int Id { get; set; }
        public Nullable<int> TotalToken { get; set; }
        public Nullable<int> BalanceToken { get; set; }
        public int UserId { get; set; }
        public string MessageStatus { get; set; }
    }


  

}
